### PR TITLE
Drawer options

### PR DESCRIPTION
**Pull request by benhylau**
cjdns-ui-2

### CODE REVIEW

**Comment by benhylau** [comment]
Also renamed `MeshnetService` to `CjdnsService`. That's okay right?

**Comment by benhylau** [comment]
Dagger is for later. Components like the `Logger` will be provided through the `CjdnsApplication.DefaultModule`, but more importantly we will provide peering credentials via mocked up Modules during development.

**Comment by lgierth** [comment]
Looks good, I'm fine with whatever rename you propose. The idea behind MeshnetService vs. CjdnsService was to only call the bits directly related running cjdroute this way, to avoid confusion moving forward. The service will probably eventually not only take care of executing CjdrouteTask, but also managing wifi etc.

Here's how you kill cjdroute, btw :) https://github.com/BerlinMeshnet/cjdns-android/blob/master/src/main/java/berlin/meshnet/cjdns/MeshnetService.java#L71-L75

I don't remember why I added that to the service instead of the task.

**Comment by benhylau** [comment]
The reason I renamed was because I intend to merge the Task into CjdnsService, and make CjdnsService an IntentService. This allows third-party apps to start cjdns via an Intent, and the Process will start in the background. Management of WIFI, fetching from peerStats, will be via a different component.

See second last comment [here](https://github.com/BerlinMeshnet/cjdns-android/issues/8).

**Comment by dpsm** [comment]
LGTM

**Pull request merged**
