### PR TITLE
Added Me page with mock data producer

### PR DESCRIPTION
**Pull request by benhylau**
device-2015-01-21-085344

### CODE REVIEW

**Comment by kpcyrd** [comment]
:+1:

**Comment by benhylau** [comment]
@prurigro @ansuz @lgierth @kpcyrd It would be cool if we can display a visualization with that empty space at the bottom of this page. Like [fc00.org](http://www.fc00.org/) but of your immediate peers only. Just an idea :wink:

**Comment by kpcyrd** [comment]
Like this? https://github.com/kpcyrd/yrd#show-your-neighbors-peerstats

Maybe you can use `yrd` as example on how to pull the data out of the admin api.

Feel free to ping me on hypeirc if you need help.

**Comment by benhylau** [comment]
@kpcyrd Cool thanks. Yes that data, but drives a visual representation, so it's easy to tell how well-connected my own node is.

**Comment by cschmittiey** [comment]
Yeah, @ansuz 's work with fc00 is probably the closest to what you're
looking for

**Comment by benhylau** [comment]
@cschmittiey Yes, I was thinking a `WebView` loading a static file pre-populated with the node data. Something like this: http://bl.ocks.org/mbostock/4062045

Anyone volunteers to do the JS?

**Comment by ansuz** [comment]
when is the static file generated? if it's done by the app, java is probably the best fit, yea?

**Comment by benhylau** [comment]
@ansuz it would be done by the app. Native Android implementation in Java would be great, though JS through a `WebView` isn't all that horrible. Issue moved here https://github.com/BerlinMeshnet/cjdns-android/issues/17.

**Pull request merged**
