### PR TITLE
Actionbar and navigation drawer

### PR DESCRIPTION
**Pull request by benhylau**
cjdns-ui

### CODE REVIEW

**Comment by benhylau** [comment]
My version of the WIP commit is not the same as yours because I rebased to master from that branch and then forced a commit. Also updated Gradle, so you would probably need to update Android Studio to build.

**Comment by kpcyrd** [comment]
Looks awesome, thank you!

**Comment by benhylau** [comment]
:+1:

**Comment by lgierth** [comment]
Niiice :)

**Comment by cschmittiey** [comment]
:+1:

**Pull request merged**
